# Use the official Node.js image.
FROM node:lts-bookworm-slim

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install production dependencies.
RUN npm install

# Copy the local code to the container
COPY . .

# Run the benchmark script
CMD ["node", "benchMark.js"]
